INFO 2016-11-14 15:23:56,179 
frontend.views.all_job.frontend_job_cancel,Deluxe,Cancel a UAVJOB Successed.{ID:1,uav_id:5,job_id:35,confirm:False,uav_job_detail_id:16}
INFO 2016-11-14 15:24:02,786 
frontend.views.all_job.frontend_job_cancel,Deluxe,Cancel a UAVJOB Successed.{ID:1,uav_id:4,job_id:35,confirm:False,uav_job_detail_id:15}
WARNING 2016-11-14 15:24:20,879 
frontend.views.all_job.frontend_job_cancel,Deluxe,Cancel a UAVJOB Failed. The UAVJOB already Confirmed.{ID:1,uav_job_detail_id:1}
INFO 2016-11-14 15:26:36,930 
frontend.views.all_job.frontend_job_cancel,Deluxe,Cancel a UAVJOB Successed.{ID:1,uav_id:4,job_id:1,confirm:False,uav_job_detail_id:5}
ERROR 2016-11-14 15:27:06,016 
frontend.views.all_job.frontend_job_cancel,Deluxe,Cancel a UAVJOB Failed. {ID:1,uav_job_detail_id:5}
Traceback (most recent call last):
  File "C:\uav\frontend\views\all_job\frontend_job_cancel.py", line 26, in frontend_job_cancel
    jobdetail = UAV_Job_Detail.objects.get(id=jobdetail_id)
  File "C:\Python34\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python34\lib\site-packages\django\db\models\query.py", line 334, in get
    self.model._meta.object_name
model.models.DoesNotExist: UAV_Job_Detail matching query does not exist.

ERROR 2016-11-14 15:27:20,063 
frontend.views.all_job.frontend_job_cancel,Deluxe,Cancel a UAVJOB Failed. {ID:1,uav_job_detail_id:5}
Traceback (most recent call last):
  File "C:\uav\frontend\views\all_job\frontend_job_cancel.py", line 26, in frontend_job_cancel
    jobdetail = UAV_Job_Detail.objects.get(id=jobdetail_id)
  File "C:\Python34\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python34\lib\site-packages\django\db\models\query.py", line 334, in get
    self.model._meta.object_name
model.models.DoesNotExist: UAV_Job_Detail matching query does not exist.

ERROR 2016-11-14 15:27:44,689 
frontend.views.all_job.frontend_job_cancel,Deluxe,Cancel a UAVJOB Failed. {ID:1,uav_job_detail_id:5}
Traceback (most recent call last):
  File "C:\uav\frontend\views\all_job\frontend_job_cancel.py", line 26, in frontend_job_cancel
    jobdetail = UAV_Job_Detail.objects.get(id=jobdetail_id)
  File "C:\Python34\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python34\lib\site-packages\django\db\models\query.py", line 334, in get
    self.model._meta.object_name
model.models.DoesNotExist: UAV_Job_Detail matching query does not exist.

INFO 2016-11-14 15:28:55,693 
frontend.views.all_job.frontend_job_cancel,Deluxe,Cancel a UAVJOB Successed.{ID:1,uav_id:7,job_id:35,confirm:False,uav_job_detail_id:14}
WARNING 2016-11-14 15:29:28,928 
frontend.views.all_job.frontend_job_cancel,Deluxe,Cancel a UAVJOB Failed. The UAVJOB already Confirmed.{ID:1,uav_job_detail_id:1}
ERROR 2016-11-14 15:30:45,400 
frontend.views.all_job.frontend_job_cancel,Deluxe,Cancel a UAVJOB Failed. {ID:1,uav_job_detail_id:14}
Traceback (most recent call last):
  File "C:\uav\frontend\views\all_job\frontend_job_cancel.py", line 26, in frontend_job_cancel
    jobdetail = U1AV_Job_Detail.objects.get(id=jobdetail_id)
NameError: name 'U1AV_Job_Detail' is not defined

